Fix webview memory leaks
OutSystems/WebView pull request #253
Opened 2022-05-06 14:27 UTC by brunocunhasilva

After updating CefGlue to a version that addressed a few leaks in that component, I found a few other leaks on the `WebViewControl-Avalonia` as well.
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11468067/167151850-8a9f01af-d26c-4eed-a315-bd50a5135924.png">

I also noted that the `WebView.Avalonia.InternalDispose()` wasn't being called when the `WebView` was explicitly Disposed:
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11468067/167153022-3045ed69-5e6a-43f3-a1fc-84bebe653f70.png">

2022-05-10 09:59 UTC, joaompneves requested changes

2022-05-10 09:59 UTC, joaompneves commented on WebViewControl/WebView.cs
> +        partial void PartialsInnerDispose();
```suggestion
        partial void ExtraDispose();
```

2022-05-10 09:59 UTC, joaompneves commented on WebViewControl/WebView.cs
> +        private void DetachChromiumHandlers() {
I dont see a reason for having this... the reports dont show problems here... you need to cut off the roots not the leafs

2022-05-11 10:31 UTC, joaompneves commented
Are there any relevant changes in the PR?

2022-05-11 11:30 UTC, brunocunhasilva commented
> 

The relevant changes are the Update of CefGlue.Avalonia and the bump of the WebViewControl.Avalonia version

2022-05-11 11:51 UTC, brunocunhasilva commented
Replaced the PR with this other one that only updates CefGlue and bumps the version
https://github.com/OutSystems/WebView/pull/254

2022-05-11 11:51 UTC, closed without merging